---
- name: Configurando o BIND
  copy:
    src: '{{ item }}'
    dest: '/etc/bind/'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items:
  - 'named.conf.local'
  - 'named.conf.options'
  notify:
  - Reload Bind9

- name: Configurando os arquivos de Zona
  copy:
    src: '{{ item }}'
    dest: '/var/cache/bind'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items:
    - 'db.dexter.interna'
    - 'rev.dexter.interna'
  notify:
  - Reload Bind9
...
